name: Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'develop'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-release
            
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Install Dependencies
        run: sudo apt install mingw-w64 libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglx-dev libgl1-mesa-dev libxxf86vm-dev
      
      - name: Build Linux
        run: ./build_linux.sh
      
      - name: Build Windows
        run: ./build_win.sh
          
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Notenrechner*"
          token: ${{ secrets.GITHUB_TOKEN }}
